# Generated by Django 2.0 on 2019-07-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='设备名称')),
                ('company', models.CharField(max_length=50, verbose_name='设备品牌')),
                ('model', models.CharField(max_length=50, verbose_name='设备型号')),
                ('area', models.CharField(max_length=50, verbose_name='存放区域')),
                ('purchase_date', models.DateField(verbose_name='购买日期')),
                ('mex_date', models.DateField(verbose_name='维保到期')),
                ('manager_addr', models.TextField(blank=True, max_length=200, verbose_name='管理地址')),
                ('business_addr', models.CharField(blank=True, max_length=255, verbose_name='业务地址')),
                ('username', models.CharField(max_length=50, verbose_name='登录账号')),
                ('password', models.CharField(max_length=50, verbose_name='登录密码')),
                ('sn_number', models.CharField(blank=True, max_length=60, verbose_name='设备序列号')),
                ('device_type', models.CharField(blank=True, choices=[('1', 'PC机'), ('2', '机架服务器'), ('3', '小型机'), ('4', '网络设备'), ('5', '安全设备'), ('6', '存储设备'), ('7', '其他')], max_length=30, verbose_name='设备类型')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='管理IP')),
                ('mac', models.CharField(blank=True, max_length=32, unique=True, verbose_name='mac地址')),
                ('account', models.CharField(blank=True, max_length=32, verbose_name='账号')),
                ('password', models.CharField(blank=True, max_length=32, verbose_name='密码')),
                ('other_ip', models.CharField(blank=True, max_length=100, verbose_name='其它IP')),
                ('asset_no', models.CharField(blank=True, max_length=50, verbose_name='资产编号')),
                ('asset_type', models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '容器'), ('4', '云主机')], max_length=30, null=True, verbose_name='设备类型')),
                ('status', models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '异常'), ('5', '其它')], max_length=30, null=True, verbose_name='设备状态')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='操作系统')),
                ('vendor', models.CharField(blank=True, max_length=50, verbose_name='设备厂商')),
                ('up_time', models.CharField(blank=True, max_length=50, verbose_name='上架时间')),
                ('cpu_model', models.CharField(blank=True, max_length=100, verbose_name='CPU型号')),
                ('cpu_num', models.CharField(blank=True, max_length=100, verbose_name='CPU数量')),
                ('memory', models.CharField(blank=True, max_length=30, verbose_name='内存大小')),
                ('disk', models.CharField(blank=True, max_length=255, verbose_name='硬盘信息')),
                ('sn', models.CharField(blank=True, max_length=60, verbose_name='SN号码')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='所在位置')),
                ('environment', models.CharField(blank=True, choices=[('1', '开发环境'), ('2', '测试环境'), ('3', '预发布环境'), ('4', '生产环境')], max_length=32, verbose_name='环境')),
                ('remarks', models.TextField(blank=True, max_length=200, verbose_name='备注信息')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hostmodel',
            unique_together={('hostname', 'ip')},
        ),
    ]
