# Generated by Django 2.0 on 2019-07-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmodel',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除,1删除，0正常'),
        ),
    ]
