# Generated by Django 2.0 on 2019-07-11 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_hostmodel_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除,1删除，0正常'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
