# Generated by Django 2.0 on 2019-07-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20190711_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmodel',
            name='ssh_port',
            field=models.IntegerField(default=22, verbose_name='ssh端口'),
        ),
    ]
