# Generated by Django 2.0 on 2019-07-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_hostmodel_ssh_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmodel',
            name='ssh_port',
            field=models.CharField(default='22', max_length=32, verbose_name='ssh端口'),
        ),
    ]
